spring:
  datasource:
    url: jdbc:h2:mem:db
    username: jefao
    password: jefao123
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
