remote:
  datasource:
    jdbcUrl: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver

local:
  datasource:
    jdbcUrl: jdbc:h2:mem:db
    username: jefao
    password: jefao123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
